// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Force re-evaluation of types
type DB = Database;

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  let SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
  let SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  
  console.log('Environment check:', {
    VITE_SUPABASE_URL: !!import.meta.env.VITE_SUPABASE_URL,
    VITE_SUPABASE_PUBLISHABLE_KEY: !!import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
    SUPABASE_URL: !!import.meta.env.SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY: !!import.meta.env.SUPABASE_PUBLISHABLE_KEY,
  });

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.error('Missing Supabase credentials:', {
      url: SUPABASE_URL,
      key: SUPABASE_PUBLISHABLE_KEY ? 'present' : 'missing'
    });
    throw new Error(
      `Missing Supabase environment variables. URL: ${!!SUPABASE_URL}, Key: ${!!SUPABASE_PUBLISHABLE_KEY}`
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

